\begin{titlepage}
\begin{center}
    
    {\huge UNIVERSIDAD NACIONAL AGRARIA LA MOLINA}\\[1cm]
    {\huge FACULTAD DE AGRONOMÍA}\\[1cm]
    {\large work's title?}\\[1cm]

\includegraphics[width=0.4\linewidth]{UNALM picture?}\\[1cm] 

   {\Large Author}\\[1cm]
   {\large TESIS PARA OPTAR EL TÍTULO DE INGENIERO AGRÓNOMO}\\[1cm]
   {\large Lima - Perú}\\
   {\large  2014}
       
\end{center}
\end{titlepage}